spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=studymap;encrypt=false
    username: sa
    password: Mfcatl007
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  servlet:
    multipart:
      max-file-size: 15GB
      max-request-size: 15GB
study-map:
  jwt:
    secret-key: 'NLTFICGRV1AJQTCNMVFPBQVVSC1MTJC55SFVCYPTNYBLJ1GQ3GB5L9AHOM7YJTYG'

twilio:
  accountSid: 'AC87b1ad87496703670ec2a1b7bf1bf89e'
  apiKeySid: 'SKf2cda581323a24cc38686619367af498'
  apiKeySecret: 'yA2sBq3Pnm0gKO3sKeB71o89LEFeYaZL'